name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Lint con pylint
        run: |
          pip install pylint
          pylint src/app.py || true

      - name: Ejecutar tests
        run: PYTHONPATH=. pytest

      - name: Coverage y HTML
        run: |
          pip install coverage
          coverage run -m pytest
          coverage report
          coverage html

